/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.Controladora;
import Logica.Tipo_de_targetas;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Josue Marquetti
 */
public class Insertar_Targeta_2 extends javax.swing.JFrame {
    
    private Controladora controladora;
    private Tipo_de_targetas tipo;
    
    
    /**
     * Creates new form Vender_Targeta
     * @param controladora
     * @param tipo
     */
    public Insertar_Targeta_2(Controladora controladora, Tipo_de_targetas tipo) {
        this.controladora = controladora;
        this.tipo = tipo;
        try{
        initComponents();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error inesperado.");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        idTXT = new javax.swing.JTextField();
        regisLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentarioTxt = new javax.swing.JTextField();
        regisxt = new javax.swing.JTextField();
        idText = new javax.swing.JLabel();
        cancelatButon = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        cantidadLabel = new javax.swing.JLabel();
        cantNumText = new javax.swing.JTextField();
        idSerieLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(montar_imagen());
        imagen.setToolTipText("");
        imagen.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setText(tipo.getNombre());

        codigoLabel.setText("ID:");

        idTXT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTXTKeyTyped(evt);
            }
        });

        regisLabel.setText("Registradas por:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Comentarios:");

        jButton1.setText("Aceptar");
        jButton1.setNextFocusableComponent(cancelatButon);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        comentarioTxt.setNextFocusableComponent(jButton1);
        jScrollPane1.setViewportView(comentarioTxt);

        regisxt.setNextFocusableComponent(comentarioTxt);

        idText.setText(valor_targeta());

        cancelatButon.setText("Cancelar");
        cancelatButon.setNextFocusableComponent(cancelatButon);
        cancelatButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelatButonActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Targetas continuas");

        cantidadLabel.setText("Cantidad:");

        cantNumText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        idSerieLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(regisLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(codigoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idTXT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(regisxt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(idText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cantNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(idSerieLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(cancelatButon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cantidadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cantNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(regisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regisxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idSerieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelatButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idTXTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTXTKeyTyped
        if(evt.getKeyChar() != '\b'&&!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_idTXTKeyTyped

    private void cancelatButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelatButonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelatButonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*
        if(vendidaBoton.isSelected()){
            
                //Codigo, vendedor, cliente, comentario
                this.targeta.setCodigo(codigoTxt.getText());
                this.targeta.setVendedor(VendedorText.getText());
                this.targeta.setCliente(clienteTxt.getText());
                this.targeta.actualiza_comentarios(comentarioTxt.getText());
                this.targeta.setEstado_de_compra(2);
                
            finalizar();
        }else if(deudaBoton.isSelected()){
            if(!codigoTxt.getText().equalsIgnoreCase("") ||!VendedorText.getText().equalsIgnoreCase("") ||
                    !clienteTxt.getText().equalsIgnoreCase("")){
                
                this.targeta.setCodigo(codigoTxt.getText());
                this.targeta.setVendedor(VendedorText.getText());
                this.targeta.setCliente(clienteTxt.getText());
                this.targeta.actualiza_comentarios(comentarioTxt.getText());             
                this.targeta.setEstado_de_compra(3);
                
                finalizar(); 
            }else{
                JOptionPane.showMessageDialog(null, "Por favor rellene los espacios señalados con color rojo.");
                
                codigoLabel.setForeground(Color.red);
                vendedorLabel.setForeground(Color.red);
                clienteLabel.setForeground(Color.red);
                
            }
            
            
        }else
            JOptionPane.showMessageDialog(null, "Por favor indique el estado de venta de la targeta.");
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insertar_Targeta_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Insertar_Targeta_2(new Controladora(),new Tipo_de_targetas()).setVisible(true);
        });
    }
    
    private ImageIcon montar_imagen() throws SQLException{
        ImageIcon imagenI;
        imagenI = new ImageIcon();
        
        try{
        byte [] imagenBytes;
        
        int id = tipo.getId();
        int cant = controladora.descargar_imagen(id).length;
        imagenBytes = new byte[cant];
        imagenBytes = controladora.descargar_imagen(id);
        
        imagenI = new ImageIcon(imagenBytes);    
        
        imagenI = new ImageIcon(imagenI.getImage().getScaledInstance(this.imagen.getWidth(), this.imagen.getHeight(), Image.SCALE_DEFAULT));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo cargar la imagen.");
        }
        return imagenI;
    }
    
    private String valor_targeta(){
        String valor;
        int precio = (int) tipo.getValor();
        if(tipo.getCuc())
            valor = String.valueOf(precio) + " CUC";
        else
            valor = String.valueOf(precio) + " MN";
        
        return valor;
    }
    
    private String serieLabel(){
        String serie = "";
        
        if(cantNumText.getText().equalsIgnoreCase("")){
            serie = idTXT.getText();
        }
        else{
            
            String serieP = idTXT.getText();
            char caracteres[]= new char[5];
            serieP.getChars(serieP.length()-5, serieP.length(), caracteres, 0);
            serie = Arrays.toString(caracteres);
            serie = serie.replaceAll(", ", "");
            serie = serie.replace("[", "");
            serie = serie.replace("]", "");   
            
            
            int cantidadT = Integer.parseInt(cantNumText.getText());
            
            int id
            
        }
        
        return serie;
    }
    /*
    private void finalizar(){
        
        
        if(JOptionPane.showConfirmDialog(null, "Esta seguro que desea continuar, los cambios no se pueden revertir.")==JOptionPane.YES_OPTION){
            try {    
                controladora.buscar_targeta_vender_4(this.targeta, this.posicion);
                JOptionPane.showMessageDialog(null, "Operacion realizada con exito.");
                dispose();
            } catch (SQLException ex) {
                    Logger.getLogger(Insertar_Targeta_2.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error inesperado, por favor reinicie la aplicacion.");
            }     
        }
        
    }
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelatButon;
    private javax.swing.JTextField cantNumText;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField comentarioTxt;
    private javax.swing.JLabel idSerieLabel;
    private javax.swing.JTextField idTXT;
    private javax.swing.JLabel idText;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel regisLabel;
    private javax.swing.JTextField regisxt;
    // End of variables declaration//GEN-END:variables
}
