/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.Controladora;
import Logica.Targeta;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Josue Marquetti
 */
public class Vender_Targeta_3 extends javax.swing.JFrame {
    
    private Controladora controladora;
    private Targeta targeta;
    private int posicion;
    
    
    /**
     * Creates new form Vender_Targeta
     * @param controladora
     * @param targeta
     */
    public Vender_Targeta_3(Controladora controladora, Targeta targeta) {
        this.controladora = controladora;
        this.targeta = targeta;
        this.posicion = Integer.parseInt(targeta.getCodigo());
        try{
        initComponents();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error inesperado.");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vendidaBoton = new javax.swing.JRadioButton();
        deudaBoton = new javax.swing.JRadioButton();
        codigoLabel = new javax.swing.JLabel();
        codigoTxt = new javax.swing.JTextField();
        vendedorLabel = new javax.swing.JLabel();
        clienteLabel = new javax.swing.JLabel();
        clienteTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentarioTxt = new javax.swing.JTextField();
        VendedorText = new javax.swing.JTextField();
        idText = new javax.swing.JLabel();
        cancelatButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        try{
            imagen.setIcon(montar_imagen());
    	}catch(Exception e){
    	    JOptionPane.showMessageDialog(null, "Error al montar la imagen.");
    	}	
        imagen.setToolTipText("");

        jLabel1.setText("Numero de Targeta:");

        vendidaBoton.setText("Targeta Vendida");
        vendidaBoton.setNextFocusableComponent(deudaBoton);
        vendidaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendidaBotonActionPerformed(evt);
            }
        });

        deudaBoton.setText("Targeta en Deuda");
        deudaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deudaBotonActionPerformed(evt);
            }
        });

        codigoLabel.setText("Codigo:");

        codigoTxt.setNextFocusableComponent(vendidaBoton);
        codigoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoTxtKeyTyped(evt);
            }
        });

        vendedorLabel.setText("Vendedor:");

        clienteLabel.setText("Cliente:");

        clienteTxt.setText("Anonimo");
        clienteTxt.setNextFocusableComponent(comentarioTxt);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Comentarios:");

        jButton1.setText("Vender");
        jButton1.setNextFocusableComponent(cancelatButon);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        comentarioTxt.setNextFocusableComponent(jButton1);
        jScrollPane1.setViewportView(comentarioTxt);

        VendedorText.setNextFocusableComponent(comentarioTxt);

        idText.setText(targeta.getId());

        cancelatButon.setText("Cancelar");
        cancelatButon.setNextFocusableComponent(cancelatButon);
        cancelatButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelatButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vendedorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(codigoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codigoTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(VendedorText, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(idText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deudaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vendidaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(clienteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addGap(2, 2, 2))
                            .addComponent(cancelatButon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vendidaBoton)
                    .addComponent(codigoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deudaBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vendedorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VendedorText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clienteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelatButon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void vendidaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendidaBotonActionPerformed
        vendidaBoton.setSelected(true);
        deudaBoton.setSelected(false);
    }//GEN-LAST:event_vendidaBotonActionPerformed

    private void deudaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deudaBotonActionPerformed
        vendidaBoton.setSelected(false);
        clienteTxt.setText("");
        deudaBoton.setSelected(true);    }//GEN-LAST:event_deudaBotonActionPerformed

    private void codigoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoTxtKeyTyped
        if(evt.getKeyChar() != '\b'&&!(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9')){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_codigoTxtKeyTyped

    private void cancelatButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelatButonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelatButonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(vendidaBoton.isSelected()){
            
                //Codigo, vendedor, cliente, comentario
                this.targeta.setCodigo(codigoTxt.getText());
                this.targeta.setVendedor(VendedorText.getText());
                this.targeta.setCliente(clienteTxt.getText());
                this.targeta.actualiza_comentarios(comentarioTxt.getText());
                this.targeta.setEstado_de_compra(2);
                
            finalizar();
        }else if(deudaBoton.isSelected()){
            if(!codigoTxt.getText().equalsIgnoreCase("") ||!VendedorText.getText().equalsIgnoreCase("") ||
                    !clienteTxt.getText().equalsIgnoreCase("")){
                
                this.targeta.setCodigo(codigoTxt.getText());
                this.targeta.setVendedor(VendedorText.getText());
                this.targeta.setCliente(clienteTxt.getText());
                this.targeta.actualiza_comentarios(comentarioTxt.getText());             
                this.targeta.setEstado_de_compra(3);
                
                finalizar(); 
            }else{
                JOptionPane.showMessageDialog(null, "Por favor rellene los espacios señalados con color rojo.");
                
                codigoLabel.setForeground(Color.red);
                vendedorLabel.setForeground(Color.red);
                clienteLabel.setForeground(Color.red);
                
            }
            
            
        }else
            JOptionPane.showMessageDialog(null, "Por favor indique el estado de venta de la targeta.");
        
             
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender_Targeta_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Vender_Targeta_3(new Controladora(),new Targeta()).setVisible(true);
        });
    }
    
    private ImageIcon montar_imagen() throws SQLException{
        ImageIcon imagenI;
        imagenI = new ImageIcon();
        byte [] imagenBytes;
        
        int id = controladora.devolver_id_imagen(targeta.getTipo_de_targeta());
        int cant = controladora.descargar_imagen(id).length;
        imagenBytes = new byte[cant];
        imagenBytes = controladora.descargar_imagen(id);
        
        imagenI = new ImageIcon(imagenBytes);    
        
        imagenI = new ImageIcon(imagenI.getImage().getScaledInstance(this.imagen.getWidth(), this.imagen.getHeight(), Image.SCALE_DEFAULT));
        
        return imagenI;
    }
    
    private void finalizar(){
        
        
        if(JOptionPane.showConfirmDialog(null, "Esta seguro que desea continuar, los cambios no se pueden revertir.")==JOptionPane.YES_OPTION){
            try {    
                controladora.buscar_targeta_vender_4(this.targeta, this.posicion);
                JOptionPane.showMessageDialog(null, "Operacion realizada con exito.");
                dispose();
            } catch (SQLException ex) {
                    Logger.getLogger(Vender_Targeta_3.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Error inesperado, por favor reinicie la aplicacion.");
            }     
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VendedorText;
    private javax.swing.JButton cancelatButon;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JTextField clienteTxt;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoTxt;
    private javax.swing.JTextField comentarioTxt;
    private javax.swing.JRadioButton deudaBoton;
    private javax.swing.JLabel idText;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel vendedorLabel;
    private javax.swing.JRadioButton vendidaBoton;
    // End of variables declaration//GEN-END:variables
}
